import java.io.*;
import java.util.*;

public class Driver{

    public static void main(String[] args){
	StringProcessor sp = new StringProcessor(
"
Monday, June 2, 2014

In the Heat of the Night - Period 3
             


1)This film won five Academy Awards, including the 1967 award for Best Picture. Do you think it was a great film? If so, why?

2)The evolving relationship between Chief Gillespie (Rod Steiger)and Detective Virgil Tibbs (Sidney Poitier) is one of the most compelling aspects of the film. Discuss their relationship.

3) The quote They call me Mister Tibbs! was listed as number 16 on the American Film Institute's 100 Years...100 Movie Quotes, a list of top film quotes. Why do you think it is so famous? 

4)Why do you think the scene where detective Tibbs slaps Eric Endicott caused so much controversy? Read the article below to find out the true story behind “one of the most revolutionary acts committed to film.”
b) Also, read about why Poitier was reluctant to shoot the film in the South and discuss your             reaction to his experience as a black actor in the Sixties. 

http://www.independent.co.uk/arts-entertainment/films/features/story-of-the-scene-in-the-heat-of-the-night-1967-1676905.html

5)How is Sidney Poitier’s character a radical departure from traditional depictions of African-American in film? Reference films we watched earlier such as D.W. Griffith The Birth of Nation and Gone With the Wind.

6)Many of you have recently watched Lee Daniel’s The Butler. Which film is more effective as a teaching tool in terms of understanding the civil rights era?

7) In the Heat of the Night came out the same year as Guess Who Is Coming to Dinner, which dealt with the controversial topic of interracial marriage. Interracial marriage was illegal in 17 states until June of 1967, six months before the film was released, when anti-miscegenation laws were invalidated by the Supreme Court in Loving v. Virginia. We watched a powerful scene in which Dr. John Prentice (Sidney Poitier) has a huge fight with his father over his love for the Joanna Drayton. Are there any movies today that deal with contemporary racial tensions? Are there any African-American actors that have the stature, charisma and cultural influence that Poitier had in the Sixties?  


Posted by Mr. Sandler 's History Blog at 12:58 PM 
Email This
BlogThis!
Share to Twitter
Share to Facebook
Share to Pinterest

28 comments:

Natalie RubyJune 3, 2014 at 3:38 PM
Watching In the Heat of the Night was gripping in a way that films from this era, like The Butler aren't quite anymore. Sydney Poitier and Rod Steiger's performance were intense and realistic, really embodying the spirit of racism, evident in both blacks and whites. The movie had a lot of symbolic aspects to it, despite just the slap. The contrast between the different African American characters, such as between Mr. Tibbs, the butler, and the sharecroppers, displayed the tiers within the Black Community, and the different expectations/ opportunities for African Americans in the South and the North. However, I'm a bit confused as to the interaction between Tibbs and the butler, and the significance of it. Certainly, it was an important landmark to serve an African American in a white, plantation-owners house, and so Tibbs took advantage of that. But he did not address the butler with respect, quite, but more with authority, which was odd, considering. 
The scenes that took place at the diner were amazingly done, in my opinion. The heat, the stench, the stickiness - it all came across to me, and the server made me feel uncomfortable through the screen. I really felt apart of the time period during those scenes in particular, and enjoyed the realistic vehemence with which the server refused to serve Tibbs. 
Sydney Poitier's character really was a radical departure from what we had earlier seen, especially in comparison to A Birth of a Nation which has unveiled racism evident within it. I feel that because he was a playing a man of his time, really affected by discrimination and the Civil Rights and Black Power movements, that Sydney Poitier could embody the strong, African American lead that Mr. Tibbs was.

Reply

hermioneJune 3, 2014 at 4:01 PM
I thought In the Heat of the Night was a great movie, not just because of Sidney Poitier's acting, but also because of how well it embodied the spirit of the 60s. Because In the Heat of the Night was filmed in the late 6s, the racist ideology of the people who lived in Southern towns and little details like the law jockey in front of Endicott’s mansion. In addition, the movie did well to portray the “obvious” shows of racism, like when Virgil Tibbs is surrounded by a gang of white boys, threatening him. The movie also showed the “quieter” side of racism and microaggressions, such as when Delore’s brother said he didn’t want Tibbs in the room, Henshaw refusing to serve Tibbs, and Tibbs consistently being called “boy” by the other police officers. Perhaps the most interesting aspect of In the Heat of the Night was the evolution of the relationship between Chief Gillespie and Detective Tibbs, which brought the heart to the movie. From the initially racist treatment that Gillespie witnessed and did nothing to change, to Gillespie walking away from another police officer who informed Gillespie that “the last chief we had would’ve bashed [Tibb’s] head in”. The final scene, where Gillespie tells Tibbs to take care of himself really solidifies the change in Gillespie, and his respect for the intelligence that Tibbs possesses. - Eda Tse

Reply

Julian KalogerakisJune 3, 2014 at 4:44 PM
In the Heat of the Night deserved all of its academy awards without a doubt; the film was so powerful in its language and acting that it compelled audiences of its time and still resonates with savvy film critics such as ourselves. In fact, in comparison to Birth of a Nation, The Butler, and Gone With The Wind, I believe it was more interesting and exciting movie. The Butler had its historical inaccuracies, as Eugene Allen never had a son named Louis who was involved with the SCLC, but really the thing that separated it from In the Heat of the Night was that it was meant to document a very specific portion of that history and then expanded as it went along to accommodate for a more generic viewpoint. This contrasted In the Heat of the Night in that it failed to use a self contained plot to truly represent the general zeitgeist of the time. In the Heat of the Night also beat out Birth of a Nation and Gone With The Wind because of its social and moral significance; the message delivered through the slap heard around the world and moments such as They call me Mr. Tibbs! really were appealing both to civil rights activists of the time and the general audience in today's theaters. This is not to say the relevance of the topic has diminished, also, as the film can now be seen more as the ultimate insight into prejudiced roots of the south with some exciting scenes characteristic of any good thriller. - Julian Kalogerakis

Reply

Ioana SolomonJune 3, 2014 at 5:01 PM
I felt utterly restless through every moment of In the Heat of the Night. What our age group would presumptuously consider a dated film was actually a masterpiece in every way. In fact, the film being shot in this time period gave us access to societally, environmentally, and behaviorally unique elements. Sydney Poitier's reactions throughout the film, most memorably the slap to Mr. Endicott's face, were certainly the result of a skillful, experienced actor. But the fact that the film was shot during the 1960s, partially in a town so dangerously racist as Mississippi, made his responses appear more genuine, more spontaneous and perhaps even easier to act. The latter isn't to devalue Poitier as an actor, it is simply to say that slapping a white man, even on set, even when practiced a thousand times, was far more convincing due to the growth of racial tensions, frustration on behalf of Black victims, and the development of the Black Power movement. It was, as the makers call it, a slap heard around the world. 

The movie was revolutionary. It eliminated the idea of black subservience and introduced a highly relatable and wonderfully convincing theme of equality through Mr. Tibbs' absolute superiority over inexperienced southern police men. It was the epitome of Black Power. 

But lastly, the white actors certainly deserve equal credit in the impact of this film. Rod Steiger (Chief Bill Gillespie) had an especially incredible role as both a weak leader and a lonely man whose respect for duty (where duty was defined as always protecting and defending whites) comes into conflict with his true moral compass. It is more difficult to appear weak than it is to appear strong, and for that Rod Steiger deserves tremendous credit. 

I would recommend this movie to anyone interested in pure acting quality not enhanced by modern technological effects, suspense, and a genuinely impactful plot.

Reply

Stephanie LinJune 3, 2014 at 5:02 PM
I personally thought that In the Heat of the Night definitely deserved all the awards and recognition it received because it was such a revolutionary film during the civil rights era. It was the first time that an African American actor was portrayed as being superior to the whites, instead of being inferior or just plain obedient, as in Gone with the Wind. It was such a drastic comparison with the Mammy figure in Gone with the Wind, because for the first time, Mr. Tibbs demanded the respect he deserved. What was also remarkable was that Gillespie eventually did give him the respect he deserved. It was amazing to see how his respect for Virgil developed from a soft get out of here to an appreciation for what he did.
I feel that this movie was more of a detective Hollywood-esque type of film than it was a film about the influence of civil rights, and that The Butler was more focused on civil rights. Cecil Gaines lived through major events of the civil rights era, from Little Rock Nine to the Voting Rights Act of 1965, and I feel like his film is more helpful in understanding the civil rights era directly. However, what people have to take into account is the fact that In The Heat of the Night was such a revolutionary film, especially the slap and the fact that Virgil knew better than the white policemen. In its time period, it was such an extraordinary film that we can accurately use it to display the racial and societal tensions that existed during that period, and how something as simple as a leading African American actor would seem normal today, but wasn't back then.

Reply

Jack YeJune 3, 2014 at 5:12 PM
I thought In the Heat of the Night was a great film that needs to be watched even today not only because of its deep plot, but also for its complete and real portrayal of the stereotypes of its time. The film has great historical accuracies which are a reason in itself for people to watch. 
One of my favorite scenes was towards the beginning, when Sam went into the train station, saw a black guy and just started searching his pockets and upon finding a lot of money, concluded that he was the murderer. It was very funny when it is later revealed that he, Mr. Tibbs, is in fact a police officer, which really shows the irony. This scene reminds me a lot of a recent autobiography I read by Richard Wright named The Ethics of Living Jim Crow which although was from the 1930s, also mentioned how Mr. Wright was questioned by policemen in the night in the South for no apparent reason. This shows how little racial discrimination had changed, and how although blacks were equal they were still separate. Another scene was when Virgil became exasperated, and yells They call me Mr. Tibbs which really showed how much power the Negro had. The scene is very famous because of its radical portray of the Negro character, which at the time, must have been a first for many movie watchers. Similarly, the slap scene also showed how powerful Virgil was, and how willing he was to stand for himself, which again must have paralyzed many watchers who were shocked. The slap really shows the gradual growth of black Americans, since decades ago, Virgil would have been shot for doing such a thing, as said by Mr. Endicott. Another aspect of the film I noticed was the change of Police Chief Bill Gillespie, who at first wanted nothing to do with Virgil, but was forced to work with him due to his team’s weakness. At the beginning, he couldn’t even trust Virgil, and even when he accepts him, plots to take the credit for capturing the criminal. As the movie progresses however, the two get closer as Gillespie even fights for him against the white mob in the shed, and even asks him to leave out of his own safety. Towards the end, when they are drinking together in Gillespie's house, we see just how close the two have become, and at the end, Gillespie sees Virgil leave, and says goodbye to him. I really liked this ending since it really shows how racism can be changed, as the racist policeman eventually grew to accept and even befriend Virgil. 
I thought Sidney Poitier did a great job portraying Virgil Tibbs, who was very different from previous black characters. While those in Birth of a Nation were seen as evil and weak, and those in Gone with the Wind were subservient, Mr. Tibbs was anything but that. From the beginning, the Negro character showed confidence, in the way he calmly handled his arrest, and intelligence. I was actually kind of shocked that the film actually focused on the superiority of the black man to the white men since previous films did nothing of the sort. In the Heat of the Night constantly reminded its audience how great a cop the black man was, and how bad a cop the white man was. 
Overall, I thought this was a great film to watch since it accurately showed what was going on during the Civil Rights Era, while also trying to persuade viewers of the greatness of the African American. Although the murder was quite tense and hot, it is the racial tensions and racial message underneath that made this movie the heat of the night. 

Reply

Tony FungJune 3, 2014 at 5:39 PM
“In the Heat of the Night” was an excellent example of the racism prevalent in the 1960s. Nowhere did Mr. Tibbs go was he not an unwelcomed figure, except in the African-American mechanic’s shop. He encountered resistance with the police, despite the fact that he was a cop. Initially, none of the white police officers believed or trusted his skills as a homicide expert because there was no way in their mind that he could’ve been more educated than he. Eventually, this African-American intellectual shows Mr. Gillespie how useful he is, and proves to everyone his usefulness. I respected how Mr. Tibbs’ could maintain his composure when he was being suspected and handled by the police officers. It would only have turned out worse had he resisted, him being an African-American.
Mr. Tibbs symbolic and shocking act of resistance was the “slap heard around the world.” It was the first time in theaters that an African-American could do that to a white man, and what made it worse was that Mr. Gillespie did nothing to retaliate. The Mr. Gillespie a week or so prior would’ve shot anyone who did that right then and there, but the new Mr. Gillespie has changed, according to the mayor. It is surprising how quickly his opinion of Mr. Tibbs has changed from treating him with the same disrespect he has towards any African-American to the utmost respect as he tells Mr. Tibbs to take care as he boards the train. Also, it was unheard of for a white man to drink wine with an African-American man, but they both greatly enjoyed that. Mr. Gillespie even trusts his insecurities with Mr. Tibbs, stating how he was probably the only soul to step foot in that house, that he doesn’t have a wife, and that he is stuck as a sheriff in a town that doesn’t even want him. No character expected this, and surely no person in the 1960s would’ve expected this either.

Reply

Sabrina BariJune 3, 2014 at 5:52 PM
This comment has been removed by the author.

Reply

Sabrina BariJune 3, 2014 at 5:53 PM
“In The Heat of the Night” was an amazing movie and I believe it deserved all of the awards it received. Although many people wouldn’t be interested in such a “dated” film, I believe that this characteristic was what truly captured our attention. Although the “Butler” is a modern film, it didn’t portray the racial tensions between the whites and the blacks during that times. In addition, “Gone With the Wind” and “Birth of a Nation” completely subordinated and degenerated the blacks. In “In The Heat of the Night,” Sidney Poiter’s character Virgil Tibbs, is an intelligent, educated black man with status. Although it was filmed in the 60’s, this film shows how blacks are equally intelligent (more intelligent in this case) as to whites. 

This film was extremely controversial at that time. The Klan was still at large and Poiter even refused to work in the south because he felt threatened. Although most of the filming was done in Illinois, one of the most radical moments in the movie was filmed in Mississippi. The “slap heard around the world” was an unscripted scene that changed the world. It was the first time that a black man dared to put his hands on a white man on the big screen. Endicott’s reaction to the slap, which was, “there was a time when I could’ve got you shot” had a great impact on the viewers at that time because it showed that although it was slow, there was hope for racial equality between the whites and the blacks. 

“In The Heat of the Night” was a fast-paced detective story which not only revealed the murderer but also revealed the horrors of American society in the 60’s. Compared to the recent films about racial inequality, this film truly portrays the tensions during that time. I think this film should be watched by the general American public because it is entertaining and educational.

Reply

Nashia ChouduryJune 3, 2014 at 5:54 PM
I really enjoyed watching “In the Heat of the Night” - it was a great film. The fact that the movie was made in the 1960s doesn’t negatively affect the quality of the film, but rather makes every moment within the film so much more impactful, because the racial tensions in the movie wasn’t just a remake of history but a present-day issue that Sidney Poitier, himself, had to face at the time. One of the most interesting scenes was the scene within Endicott’s land, where the audience was able to see the contrast between Tibbs, an educated northern African American, and the southern African American sharecroppers. I also thought that the lawn ornament that looked like a minstrel figure showed the difference between race relations in the north and south. This can also be seen through the way different people treated Tibbs. For example, the wife of the man murdered, was from the north, and treated Tibbs with respect. She insisted that he stay on the case to help solve the crime, while the young white men within the southern city attempted to kill Tibbs by cornering him. 

I also thought that Sidney Poitier’s acting was extremely powerful. When he yelled “they call me Mr.Tibbs”, he looked so exasperated by the way he was being treated, but he was also making a clear stance- he’s going to be treated equally and with the same respect as others. This is also seen in the infamous slap scene in which he slaps Endicott after Endicott slaps him. His reaction was extremely quick and showed that he wasn’t going to accept such rude treatment.

Reply

Andrey PrigovJune 3, 2014 at 6:30 PM
It's unfortunate that Norman Jewison's In the Heat of the Night never played in any theater below the Mason-Dixon line for the film represented a watershed moment in American history. This was 1967 and although the civil rights movement had achieved momentous gains (CRA of 1964, VRA of 1965), the nation had yet to come to terms with societal change. Probably nowhere was the blowback so acrimonious than in the Mississippi backcountry where white inhabitants, even in their most terrifying nightmares, could not imagine blacks being anything but poor and subservient. The appearance of Virgil Tibbs then, an educated African American police officer, serves as a tremendous slap on the face to this white community. Their agitation is captured brilliantly through facial expressions, gestures, and a deafening tension that engulfs the scene. At the same time, Jewison does not place the film's focus solely on race relations and rather builds a coherent murder mystery around the theme. The Butler had fallen into this trap; by attempting to cram an agenda down the throat of its viewers, it lost the genuinity of the movement it was portraying. The blatant racism of the era is thus better articulated through the nuances of In the Heat of the Night. In one memorable scene, Tibbs tells a black man that he'll find a motel to rest for the night. The man laughs and tells Tibbs that he's staying with him because he knows that there aren't any motels that would serve blacks. Just as the film displays division though, it also makes great leaps in promoting understanding between race. Gillespie's gradual change of heart emphasizes that animosity and ignorance could be overcome. The sanguine tone of the his final words, You take care now, y'hear, instills hope in the morality of the country. 

Reply

Razwan MiahJune 3, 2014 at 6:37 PM
I personally really enjoyed “In the Heat of the Night”. It truly deserves 5 Academy awards. I think Rod Steiger deserved his award for best actor because I really enjoyed his progression throughout the film. At first, I thought he was the average racist police officer in the South, but I was proven wrong. His relationship with Virgil was entertaining and powerful. At first he was skeptical of Virgil and reluctant to accept his help, but as the movie progressed he became more accepting of Virgil. Poitier’s performance of Virgil was exceptional, his dialogue was very powerful and his persistence appealed to me. When I heard the famous line, “They Call me Mr.Tibbs” I was amazed because I remembered that his was in the 1960s and for him to say that really reflected on the changing social atmosphere. 
The slap heard round the world is probably the scene I will remember the most. It was shocking when Virgil slapped Endicott and I told myself that Virgil is dead after that. To have an African-American slap a white man at that time was unheard of at this time. This slap reminded me of Bob Dylan’s line “The Times They are a Changing” because it shows the change American society was going through where African-Americans were starting to have equality and rights. Endicott told Virgil that “He could have had him shot if this happened before” and that’s true and makes this scene that much more powerful and historic. Poitier’s acting impressed me and can rival my favorite black actors Denzel Washington and Morgan Freeman. This film definitely did not feel dated, but the opposite for me because I enjoyed the music and sounds that were unique to film at that time. Overall, this film was entertaining, Poitier’s performance was captivating and this film really captures the social shift of the 60s era, I would definitely recommend this film to my friends. 

Reply

Christopher KimJune 3, 2014 at 6:40 PM
“In the Heat of the Night” was without a doubt a revolutionary film during the 1960s, and although the film is almost 50 years old, I still felt overwhelmed by the racial and social tensions portrayed through the impeccable acting of Sidney Poitier. Poitier’s performance as Mr. Tibbs was executed flawlessly, as he was able to capture every subtle moment and made the film incredibly natural and realistic. However, I also believe that Rod Steiger’s performance as Gillespie perfectly complemented Poitier throughout the film. 

“In the Heat of the Night” was clearly worthy of the praise and recognition that it received, as its significance during a time when civil rights was at the peak of societal discussion cannot be ignored. Mr. Tibbs’ demand for equal rights, portrayed in many scenes such as the (in)famous slap and his struggle in dealing with the white police officers, evidently reflected the desires of fellow African Americans during the time period. 

I’d definitely recommend this film; with a combination of an exciting story line and a crucial underlying meaning, “In the Heat of the Night” is worth the 2 hours.

Reply

Jessica M.June 3, 2014 at 7:31 PM
In the Heat of the Night definitely deserved those five Academy Awards. The film realistically portrayed the racism prevalent in the South during the 1960s. Although In the Heat of the Night didn't specifically focus upon the Civil Rights movement, it managed to incorporate that highly controversial issue into a Hollywood-style detective movie. Tibbs' experience in the South really struck out to me. I admired his steadfast willpower to remain despite threats from angry white Southerners and outright violence. Scenes like these, not mere statistics, truly reveal the tensions between the blacks and the whites. One of my favorite aspects of the movie was the evolving relationship between Tibbs and Chief Gillespie. I remember laughing at Gillespie when he doubted the legitimacy of Tibbs' claims (of being a police officer). Through the course of the movie, Gillespie grudgingly learns to respect Tibbs. The scene at the end when Tibbs departed was heartwarming. Seeing the two wave good-bye to each other on such good terms made me smile. It shows promise in a future where blacks and whites can live in harmony. Of course, I also really liked the infamous slapping scene between Tibbs and Endicott. Poitier is an excellent actor, responding to Endicott's slap in speedy timing. I loved the lack of hesitation on Poitier's part, as well as his expression, which just seemed to scream, What? You've got a problem with what I just did?. This was, without a doubt, revolutionary, and I'm glad that he suggested the inclusion of this scene in the movie. Sidney Poitier's role itself was pretty revolutionary as well. Unlike many black characters, Tibbs is resolute in his beliefs for equality. He is the epitome of courage and bravery against white oppression. Other black characters are often characterized as servants, or beings lower than the white characters. Tibbs, on the other hand, is shown to be much more intelligent than any of the white police officers. Overall, I really enjoyed In the Heat of the Night for its realistic portrayal and its refreshing perspective.

Reply

Jackie WangJune 3, 2014 at 7:47 PM
I was surprised In the Heat of the Night was made in the 1960s, considering the quality of the film. The movie as a whole was suspenseful and was able to portray the racism that still existed at that time. For example, Virgil was arrested for murder on the basis that he was black and he had money. He was also chased and attacked by the Southern whites. Furthermore, Rod Steiger and Sidney Poitier portray of their respective characters were convincing and made the movie much more effective.

Although, Chief Gillespie character at first seemed like the typical racism southern cop, we see his character develop and change. Gillespie was able to overcome his pride and ask Virgil for his help. He eventually befriends Virgil and cares for his safety. Their relationship shows that blacks and whites can work together and accept each other. 

On the other hand, Virgil Tibs is not your stereotypical black either. Not only is he a police officer his unexcitingly smart, serious, and easily outwits his fellow officers. This is such a sharp contrast from African-American portray in minstrel show as dimwitted fools. He is also not afraid to stand up to whites in his famous line They call me Mister Tibbs! and his immediate reaction to slap Endicott back. Endicott was portrayed as powerless and in tears. Virgil’s character painted blacks in a new light, he showed blacks had nothing to fear and his scenes advocated the equality of blacks and whites.

Reply

Aaron MortensonJune 3, 2014 at 8:03 PM
Not only does In the Heat of the Night do a fantastic job of depicting racism in the South during the Civil Rights movement, it's timing and reception help us understand the beginnings of the black power movement and give further insight into how ingrained racism was at the time. The fact that something as simple as a black man striking a white man back rather than turning the other cheek was so dramatic and controversial tells us a lot about the time. Today, the slap seems natural and, while it is a nice moment in the movie, does not seem particularly striking. This is because today, we are used to seeing strong African-American leads in movies that are more than willing to strike back. As a result, it does not surprise us that a black man stands up to a white man, and next to some scenes from movies like Django Unchained, the simple slap from In the Heat of the Night seems incredibly mild. The controversy and stir caused by what is by our standards a normal reaction shows just how shocking the Black Power movement must have been.

Reply

Eva IJune 3, 2014 at 8:13 PM
In the Heat of the Night is a great film, and it certainly deserved its academy awards. First of all, the movie was revolutionary because it not only accurately portrayed the tension between the white and the black in the South but also portrayed Virgil Tibbs, the black main character, as being superior to the whites. Compare to Gone with the Wind and The Birth of a Nation, this movie had offered a completely different view of African Americans, which perfectly echoed the Civil Rights Movement that was going on during the 60s. Compare to the whites in the movie, Virgil was not only more good looking but also more intelligent. Instead of being a traditional black servant figure, Virgil was shown as a strong and independent-minded black police officer who was not afraid to make the racist whites to treat him with respect. For this, I admire actor Sydney Poitier’s courage to take this revolutionary role in this movie. When the movie was filming in the South, Poitier was in constant fear of being harassed or attacked by racist whites. Despite the hardships, he persevered. 

The other thing I like about the movie is Officer Gillespie (Rod Steiger)’s character development. At the beginning, the Chief was depicted as a stereotypical white southerner who did not believe in racial equality. However, as the movie went on, the Chief began to trust Virgil. In the end, the Chief even invited Virgil to his house and shared his insecurities and doubts. In my opinion, a good movie should have an enthralling plot, carry a message, and have notable character development. In the Heat of the Night definitely had all three components nailed. 

Reply

Alyson LiangJune 3, 2014 at 8:27 PM
I thought that In the Heat of the Night was such a great movie to use to help us visually understand the racial prejudices and differences between whites and African Americans. The plot of an intelligent black police officer fighting against the racial prejudice of the South and eventually overcoming such difficulties while proving himself capable was not a common plot back in the 1960s and really caught the society's attention. 

I especially loved the dichotomy between Virgil and the other African Americans in Mississippi. The juxtaposition between Virgil and the African American workers at Endicott Farms showed how even though slavery was illegal and all African Americans were free, the standard of life was different. Whereas Virgil was a self-made man, had a decent salary, and a respectable job, his fellow brothers and sisters were subjected to sharecropping, picking cotton just like in the days of slavery. The scene when Virgil was in the car with Gillespie driving down to Endicott Farm just shows how distant and different the lives of blacks in the south and the lives of blacks in the north can be. It's a very powerful, but subtle scene that adds on to the overall moral of the film.

I thought that Sidney Poitier's acting was incredible. Not only was he an exceptional actor with a great presence and charisma, he was THE actor that represented the efforts of the Civil Rights Movements. His slap heard round the world echoed the success of the Civil Rights Movement, the change in society, and in the way of thinking. 

All in all, I think showing In the Heat of the Night was a great way to learn, feel, and understand the racial prejudices African Americans dealt with in the deep South. I would definitely say that watching this movie was time well spent!

Reply

Aaron LooJune 3, 2014 at 9:19 PM
Despite the fact that the film can be considered, on many levels, to be dated, it truly serves as a relic of the times as it masterfully depicts the conflict between two clashing societies in 1960s America - one where more progressive attitudes have taken root, allowing even an African-American to become a cop, and another where latent racism is abound, resisting change from the pre-Civil War social order. The racism of the police near the beginning of the movie (especially when he was arrested solely based on his race) highlights this, along with the portrayal of white, racist mobs that were seen consistently throughout the movie. Compounded with this is the fact that it was a very well made movie deserving of all of the awards it has won. Sidney Poitier's portrayal of Virgil Tibbs captures the eloquence and style that captivated the minds and hearts of audiences across America (and by across America, I mean //not// in the south), and provided a break from subservient and savage portrayals of blacks seen in Gone With the Wind and Birth of a Nation respectively. Additionally, the slap heard 'round the world is especially significant, as it symbolized a shift in social power from a white aristocracy, to a more egalitarian society, especially evidenced by Officer Gillespie's confusion and powerlessness in the situation. Overall, watching the film was an incredibly enjoyable experience, and I would very much recommend this film looking to explore a different angle of the Civil Rights era.

Reply

Alex HuJune 3, 2014 at 9:37 PM
I felt that, in some ways, In the Heat of the Night could be considered a bit outdated. There was no grand CGI effects, a distinct lack of giant explosions. The murder is committed by some person that many watching the movie probably never remembered seeing. Yet, at the same time, the quality of the film, especially given its low budget, was not lacking. It was clear that the people involved worked with what they had to the best of their ability.

More importantly, this film tackled what was an extremely controversial issue in the United States during this time; the meaning of equality, in terms of ability, opportunity, and respect, between white and colored people. Beyond all the much discussed slap heard around the world and the numerous mentions of the intelligence of the black main, a homicide detective named Vergil Tibbs, as well as the unprecedented tolerance from the white sheriff, Chief Gillespie, there are aspects of a more subtle nature.

For example, Chief Gillespie, despite trying his best to act like the stereotypical white man in the town, fails to do so as he realizes that so long as Vergil had a sound reason for whatever frustrations, Gillespie could not find it within himself to ignore his own mistakes and turn his back on the right thing to do. This belief in justice is also what causes him to actually protect Vergil from being mobbed by prejudiced young white men from town. The instances where Gillespie tries to tell Vergil to leave usually stems from his desire to finish the case quickly and not generally due to his race. This is because he knows that the sooner the case is closed, the sooner construction for the town's prosperity could resume. This is why I believe Gillespie is a representation for all the whites who are more understanding in the South - they're isolated from the majority.

Vergil Tibbs also reveals a more subtle, even darker, side to him. Through the exchange after slapping Endicott, Vergil reveals how, in some ways, he was no better than the white townspeople. After listening to Vergil vehemently swore that, given two days, he could drag that man down from the hill. Gillespie looked at Vergil, shocked, and said My god, you're no different from the rest of us, aren't you? As Vergil Tibbs represented the new movement of Black Power, which advocated the abilities of the black people, this scene also shows the possible dangers of such a movement - that black people could be just as discriminatory to whites as whites have been for the last couple of centuries.

In the Heat of the Night is a masterpiece because it does not just draw attention to the issue of racial equality, nor because it simply showed, broadly, the ideas of black power and white acceptance. Because the characters are so well portrayed, far more intricate things can be pulled from the hopes and flaws of the characters.

Reply

Terrance LJune 3, 2014 at 9:40 PM
In the Heat of the Night seems to be a great portrayal of the racial tensions of the period. This film seems particularly impactful because of the time period that it was released in: 1967 near the end of the civil rights movement. Having such a controversial and unseen theme be incorporated, the film successfully managed to grab society's attention. The theme was so controversial that the movie was banned anywhere below the Mason-Dixon line.

I enjoyed viewing the large difference between Virgil Tibbs and the other characters in the film. Similar to Uncle Tom's Cabin, the film portrays Virgil as that of a hero and even superior to the white officers in terms of knowledge and skill. At the same time, the film manages to include the racism of the period, showing mob assaults and other small scenes. The low budget and outdated technology used in the film made everything seem so much more realistic.

I particularly love the main actor Sidney Poitier, the Jackie Robinson of Hollywood, who gallantly took this role. Knowing the racism present in Mississippi, and the south, and the potential danger that he might be in, Poitier still agrees to play in the film (and thus films in Illinois). I also love the role of Virgil Tibbs, a self-made African American who ends up being on par and even above many whites. Poitier has such great presence and charisma (and even dares to hit a white man - slap heard around the world). What really ended the film well was the development of Bill Gillespie, a police chief who at first despised and persecuted Tibbs. Throughout the film, Gillespie learns to acknowledge Tibbs and did what something that was rare for a white man to do: be friends with a black man.

I really enjoyed the film “In the Heat of the Night.” It was able to portray the racial injustice against the African Americans of the time. It also avoid over-dramatizing violence or assaults like in films “The Butler” or “12 Years a Slave,” yet still manages to clearly deliver the message. The film was definitely worth watching.

Reply

Annie LinJune 3, 2014 at 9:47 PM
In the Heat of the Night was, in my opinion, a landmark film that definitely deserved all of the awards and recognition given to it. During the first ten minutes you may get the feeling that this movie is old and dated. However that is not true, though the movie was filmed in 1967 I think it adds to the effect of the movie. During many of the scenes where the main character, Virgil Tibbs, was cornered by gangs of white racists, it's very believable that they actually wished to mean him harm. The reactions the cast give are very true to the situation because they are in the period of the Civil Rights Movement and the racism is all around them.

There are also many things included in this movie that would not have been included, if the movie had been made today. One thing is the black minstrel figurine outside the plantation owner, Endicotts's, house. We today may see it just as a really racist lawn ornament, but at the time it was thought that if you touched the head of the ornament (which the police chief Gillespie did) you would receive good luck. Another thing is Virgil's reaction and Endicotts's reaction to the slap heard around the world. Both are things that occurred because of the time period the movie was filmed in. Had this movie been made today, these and other small details would have been forgotten or overlooked.

The slap heard around the world was an amazing moment in film history. This unplanned, but totally justified, reaction to a very racist comment is one of the things that makes this such a revolutionary film. Instead of the subservient slave who takes the punishment, Virgil Tibbs defies convention and retaliates. This was unprecedented because this was the era where  a few years ago I could have had you shot. 

Something that is also done really well is the character of Virgil Tibbs. It is so different from previous African American characters. Tibbs is a stark contrast to the African Americans portrayed in Birth of a Nation and Gone With the Wind because he is an educated, reasonably wealthy man. When we first encounter him he is dressed in a nice suit and has on him more money than the chief of police in the town makes in a month. Throughout the movie we see that Tibbs is able to talk circles around the other white actors, and this was just so different from what was the norm. 

This movie definitely was worth watching and gives a new perspective on the time period. When you sit in class and learn about the Civil Rights Movement you learn about riots and protests. What you don't really learn about is the extent racism in the South for African Americans,even if they held positions of authority, at this time. We get to see that in this film, but what we also see is a transformation and amazing character development throughout the film as well as the contrast between the opinions of the North and the South when it came to African Americans. We get to see a thrilling murder case headed by a man that would not have gotten a job as a factory worker if he had been from the South.The plot was very engaging and the amazing acting and attention to detail in the film make it really worth watching.

Reply

David BangJune 4, 2014 at 12:18 AM
Watching “In the Heat of the Night” was a pleasant experience that did not leave me bored at any point. While the crime mystery aspect of the plot itself was a little confusing, as some of the connections seemed incoherent or too based on assumptions, and may need a little revisiting, but the overall message of the movie was in no way deterred this. The time period and setting evidently shows the racial hate and prejudice in this small Mississippi town. Obviously, Sidney Poitier, who plays Detective Virgil Tibbs, would be hesitant to film in Mississippi, the hub of racial hatred as further evident by the necessity and dangers of the Mississippi Freedom Summer. The scenes of Virgil being ganged up on and cornered by groups of red-neck Southerners would have probably come to reality had Poitier filmed in Mississippi. For all we know, Poitier could have been like the victims of the Mississippi Freedom Summer, and ended up buried in the woods.

The setting and overall plot clearly reflect the legacy of the Jim Crow South. In a sense, it is similar to “Lee Daniel’s The Butler,” however the perspective it conveys is different. “The Butler” tended to focus directly on the political aspects of the Civil Rights Movement and, by extension, showed accurate and often graphic scenes of violence in the Jim Crow South, as evident by the white Southerners’ violent retaliation against protests, sit-ins, and marches. On the other hand, “In the Heat of the Night,” focused more on implying aspects of the Civil Rights Movement. Detective Virgil Tibbs takes a stance for himself and proves his intellectual superiority as well as his willingness to retaliate against any discrimination against him. When Virgil declares “They call me Mister Tibbs,” he is emphasizing that he is an individual that deserves and will receive respect as evident by his title. Also this quote is a play on the Jim Crow ideology that expected all Negroes to refer to all whites as “sir” or “madam” and if a Negro forgot to add this title to the end of every sentence when referring to the whites, the Negro would often receive a sort of “discipline” whether it be a slap or a beating. In this way, Negroes were forced to be inherently subservient to the whites, so when Virgil declares that he will not allow any form of disrespect, he is declaring that he will no longer allow the Negro to remain subservient to the white race.

The epitome of Virgil’s determination to resist the principles of a Jim Crow based South is evident by his retaliation slap against Endicott. To state the obvious, this slap was revolutionary in that a Negro actor had never shown such a form of defiance against the assumed superiority of whites. In my own opinion, I did not think much of the slap as my mindset is different than that of the people in the 1960s and 1970s. However, I did understand how offended Endicott was, till the point that he looked like he was going to cry, and this made me further respect Virgil. His entire character was a contrast to the centuries of how Negroes had been depicted, whether in newspapers or in filmography. Negroes would no longer stand for being portrayed as rapists, barbarians, and idiots, instead they would be portrayed as intelligent, authoritative, and committed.

Chief Gillespie (Rod Steiger) and Virgil’s relationship is interesting as it develops in a unique way. Obviously, Chief initially dislikes Virgil and sees him as inferior, a parallel to the centuries of hatred and discrimination. However, slowly but evidently, Chief begins to actually come to respect and perhaps even favor Virgil. The Chief acknowledges Virgil’s intelligence and trusts him, and eventually sees him as an equal. 

Reply
Replies

David BangJune 4, 2014 at 12:19 AM
This comment has been removed by a blog administrator.

Reply

Tina ZhengJune 4, 2014 at 2:04 AM
In the Heat of the Night definitely had a large impact in that it portrayed the racism of the 1960s really well. For a film of the 1960s, the graphics almost seem contemporary, some scenes were very comical (like when Virgil said that he was a police officer), and the subtle message of racist stereotypes it showed. I thought that the movie was more focused on the mystery rather than the racism that was prevalent at that time, but that aspect would make it appealing to modern day students. 

Sidney Poitier's acting was really impressive and whenever I think of the movie I always remember him saying I'm a police officer and They call me Mister Tibbs! Those quotes definitely struck me the most as they showed the progress of the position of an African American. The movie really contrasted Tibbs and the policemen really well and it showed how intelligent and clever African Americans could become with education. This was really different from the Birth of the Nation in which African Americans were always the unintelligent rapists. Watching part of the Birth of the Nation and then In the Heat of the Night was really useful in showing the difference between white portrayal of African Americans in the and the reality of African Americans.

I really liked the extent to which the actors were portraying their characters. For example when Steiger was playing the laid-back chief he portrayed that aspect by having his character constantly chew gum. In the end it turned out that he had chew 263 packs of gum during the shoot, which really illustrates his devotion to his role. 

Overall the movie made a really strong impression and I believed that it definitely deserved the Oscars it received because of its quality and its message.

Reply

Alexander OltarshJune 4, 2014 at 5:02 AM
In the Heat of the Night was a very entertaining film and I enjoyed watching it very much. The story was very compelling from the beginning, a successful black police detective from Philadelphia being contracted to work for the police department of a racist small town in Mississippi provided for great drama and interesting social commentary throughout. While the murder mystery was seemingly the main plot device for the film, it was the interaction between Virgil and the white characters that demanded most of the focus. One line that I enjoyed was They call me Mr. Tibbs. This showed the white characters that they needed to respect the honor and integrity of Virgil, even if it conflicted with their racist views. It was a heated line with a great amount of emotional weight attached to it. Sidney Poitier turned in a great performance as usual and Rod Steiger and Warren Oates were masterful in their secondary but critical roles. I would recommend this film to anyone who wanted to watch a terrific film that demonstrated the problems of race in 1960s Mississippi or anyone who just wanted to watch a great 1960s film in general.

Reply

Mr. Sandler 's History BlogJune 4, 2014 at 5:43 AM
The following comments were made by David Bang---This should serve as a vision for the future as similar to how Chief began to open up to Virgil, as a parallel in America, the White Southerners should and will slowly open up to the Negroes and see them as equals in due time. This process is slowly happening in due time and is even continuing to this day, and I predict that eventually we will all see a world full of whites with the Chief’s mentality and Negroes with Virgil’s abilities.

Culturally and socially, African-Americans are becoming more and more integrated and significant in society. Figures ranging for movie stars like Will Smith to political figures like Obama, are all contributing their just portion to the Civil Rights cause. This film served as a milestone as well as stepping stone for Civil Rights, so it is deserving of its awards.

Reply

Nicolette HJune 4, 2014 at 6:04 AM
In the Heat of the Night was a fantastic film, and it never occurred to me as being dated. The music, the small town, even the classic cars served to transport the viewer into the 1960s, when even the most intelligent and respectable black people were considered inferior to the poorest and most ignorant white people. The low-budget production of the film actually worked in its favor, allowing the viewer to focus on the racial undertones of the plot rather than on over-the-top special effects. 

The casting was likewise done very well. Sidney Poitier as Detective Virgil Tibbs did a wonderful job representing blacks as capable of high moral and intellectual standing, counteracting the stereotypes of the time. Chief Gillespie, too, is worthy of praise, as his dynamic performance illustrated the moral dilemmas many white people faced when it came to racial injustice. Poitier and Steiner's interactions on screen were powerful in their symbolism, especially when Tibbs declared that in the North, they call [him] Mr. Tibbs. It was this scene as well as the exchanged slaps between Tibbs and Endicott that were the most controversial. Never before had black actors had so much confidence and assertiveness on screen. It was unprecedented for a black man to hit a white man in a movie. These scenes therefore contributed greatly to the film's characterization as one that changed the course of cinema history, a rating I wholeheartedly agree with.");
    }
}